/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package airhockey.gui;

import airhockey.network.Client;

/**
 * This class contains the main of the project
 */
public class App {
    /**
     * The width of the app initialized at 800
     */
    private final int WIDTH = 800;

    /**
     * The height of the app initialized at 500
     */
    private final int HEIGHT = 500;

    /**
     * Main of the project
     * @param args an array of String written in the terminal
     */
    public static void main(String[] args){
        if(args.length > 1) {
            System.out.println("Too much arguments");
            System.exit(0);
        }
        if(args.length == 1) {
            Client.setHostname(args[0]);
        }
        MenuClient.launch(MenuClient.class, args);
    }
}
