/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package airhockey.gui;

import airhockey.network.Client;
import airhockey.network.Server;

import java.io.IOException;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;

public class App {
    private final int WIDTH = 800;
    private final int HEIGHT = 500;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args){
        if(args.length > 1) {
            System.out.println("Too much arguments");
            System.exit(0);
        }
        if(args.length == 1) {
            try {
                InetAddress add = InetAddress.getByName(args[0]);
                try {
                    DatagramSocket test = new DatagramSocket(0, add);
                    test.close();
                } catch (SocketException e) {
                    System.out.println("Can not connect with this hostname");
                    System.exit(0);
                }
            }catch(UnknownHostException e) {
                System.out.println("This hostname doesn't exist !");
                System.exit(0);
            }
            Client.setHostname(args[0]);
        }
        MenuClient.launch(MenuClient.class, args);
    }
}
